# Generated by Django 3.0 on 2020-12-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metatitle', models.TextField(max_length=60)),
                ('metadescription', models.TextField(max_length=250)),
                ('metakeywords', models.TextField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metatitle', models.TextField(max_length=60)),
                ('metadescription', models.TextField(max_length=250)),
                ('metakeywords', models.TextField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='EM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metatitle', models.TextField(max_length=60)),
                ('metadescription', models.TextField(max_length=250)),
                ('metakeywords', models.TextField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PPCM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metatitle', models.TextField(max_length=60)),
                ('metadescription', models.TextField(max_length=250)),
                ('metakeywords', models.TextField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metatitle', models.TextField(max_length=60)),
                ('metadescription', models.TextField(max_length=250)),
                ('metakeywords', models.TextField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SMO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metatitle', models.TextField(max_length=60)),
                ('metadescription', models.TextField(max_length=250)),
                ('metakeywords', models.TextField(blank=True, max_length=256)),
            ],
        ),
    ]
