# Generated by Django 3.0 on 2020-11-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20201126_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='url',
            new_name='link',
        ),
    ]
