# Generated by Django 3.0 on 2020-12-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_bloglistingpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='selectcategory',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='bloglistingpage',
            name='metadescription',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bloglistingpage',
            name='metatitle',
            field=models.TextField(max_length=60),
        ),
    ]
