# Generated by Django 3.0 on 2020-12-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20201203_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='metakeywords',
            field=models.TextField(default='', max_length=256),
        ),
    ]
