# Generated by Django 3.0 on 2020-12-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_remove_blog_metakeywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='metakeywords',
            field=models.TextField(default=''),
        ),
    ]
