# Generated by Django 3.0 on 2020-12-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mettatitle', models.CharField(max_length=256)),
                ('mettadectitle', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
