# Generated by Django 3.0 on 2020-12-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201202_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='mettadectitle',
            new_name='metadescription',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='mettatitle',
            new_name='metatitle',
        ),
        migrations.AddField(
            model_name='homepage',
            name='metakeywords',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
