# Generated by Django 3.0 on 2020-12-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201202_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='metatitle',
            field=models.TextField(max_length=256),
        ),
    ]
