# Generated by Django 3.0 on 2020-12-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201203_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='metakeywords',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
